cities=['Chang Sha','Heng Yang','Guan Zhou','Sheng Zheng']
print(cities)
cities.append('Bei Jing')
print(cities)
cities.insert(1,'Tian Jin')
print(cities)
del(cities[1])
print(cities)
temp=cities.pop()
print(cities)
print(temp)
temp=cities.pop(-1)
print(cities)
print(temp)
cities.append('London')
cities.append('London')
print(cities)
cities.remove('London')
print(cities)
cities.reverse()
print(cities)